
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: >
      sh -c "npx prisma migrate deploy && node src/app.js"
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  db_data: